### ISSUE TITLE
Thread Exception 

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/noodles#31]
When Running [qmworks](https://github.com/SCM-NV/qmworks) the following exception is thrown, after some of the dependencies are computed,
``
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/fza900/anaconda3/envs/qmworks/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/fza900/anaconda3/envs/qmworks/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home6/fza900/Prototype/qmworks/src/noodles/noodles/run/haploid.py", line 208, in patch
    sink.send(v)
  File "/nfs/home6/fza900/Prototype/qmworks/src/noodles/noodles/run/haploid.py", line 171, in sink
    f(*args)
  File "/nfs/home6/fza900/Prototype/qmworks/src/noodles/noodles/display/simple_nc.py", line 121, in __call__
    getattr(self, status)(key, data, err_msg)
  File "/nfs/home6/fza900/Prototype/qmworks/src/noodles/noodles/display/simple_nc.py", line 48, in schedule
    self.out << "\u2502 " << msg << "\n"
  File "/nfs/home6/fza900/Prototype/qmworks/src/noodles/noodles/display/pretty_term.py", line 44, in __lshift__
    self.f.write(x)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2502' in position 0: ordinal not in range(128)

But the programs keeps on running normally

**Comment by jhidding** [comment]
Weird, can you create an ascii branch and just replace the '\u2502 'with '| ' for the moment? There's some other characters that will give you trouble the X and V things. I'm currently on holiday (writing my thesis) so I can't provide a more thorough fix atm. Cheers!

**Comment by felipeZ** [comment]
that's not a big problem it is just a weird message. I will follow your suggestion

**Comment by jhidding** [comment]
Ok, we (@blootsvoets and I) found out the problem. It has to do with the terminal standard output character encoding. I will create a fallback to ASCII on top of the default UTF-8 characters.
