### ISSUE TITLE
Error initializing Xenon

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/noodles#35]
When starting the xenon error the following exception is raised:
```
  File "$HOME/prototype/noodles/noodles/run/xenon/xenon.py", line 16, in <module>
    xenon.init(log_level='ERROR')  # noqa
  File "$HOME/miniconda3/envs/qmworks/lib/python3.5/site-packages/xenon/__init__.py", line 69, in init
    raise ValueError("Classpath does not correctly specify Xenon and "
ValueError: Classpath does not correctly specify Xenon and its dependencies. This exception is fatal: calling init again will not resolve this error.
```

**Comment by blootsvoets** [comment]
Hi @felipeZ. First off, I've now made a small change in the devel branch that defers the initialisation of Xenon to the initialisation of XenonKeeper. Does that help? Bug tracking questions:
- In what code are you calling xenon?
- How was Xenon installed? With `pip install -U '.[xenon]'` with Python 3.5? Inside a virtualenv or conda environment or on the base system?

**Comment by felipeZ** [comment]
Hi @blootsvoets  I have install ``pyxenon`` in the anaconda environment using the command ``pip install .`` inside the ``pyxenon`` folder.
I'm trying to use the ``xenon`` runner of ``noodles`` see: [run_xenon](https://github.com/NLeSC/noodles/blob/master/noodles/run/xenon/__init__.py). This function is called from [qmworks](https://github.com/SCM-NV/qmworks/blob/issue-9/qmworks/packages/packages.py). The error is triggered during the import statement,


```
Traceback (most recent call last):
  File "/home/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/xenon/__init__.py", line 67, in init
    init_jvm(classpath, log_level)
  File "/home/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/xenon/java.py", line 109, in init_jvm
    nl.esciencecenter.xenon.Xenon.__javaclass__.getName()
  File "/home/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/jpype/_jpackage.py", line 55, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package nl.esciencecenter.xenon.Xenon.__javaclass__.getName is not Callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workflow_coupling.py", line 13, in <module>
    from qmworks import run, Settings
  File "/home/felipe/prototype/qmworks/qmworks/__init__.py", line 4, in <module>
    from .packages import *
  File "/home/felipe/prototype/qmworks/qmworks/packages/__init__.py", line 1, in <module>
    from .packages import *
  File "/home/felipe/prototype/qmworks/qmworks/packages/packages.py", line 15, in <module>
    from noodles.run.xenon import (run_xenon_prov, XenonConfig,
  File "/home/felipe/prototype/noodles/noodles/run/xenon/__init__.py", line 1, in <module>
    from .runner import (run_xenon, run_xenon_prov)
  File "/home/felipe/prototype/noodles/noodles/run/xenon/runner.py", line 1, in <module>
    from .dynamic_pool import DynamicPool
  File "/home/felipe/prototype/noodles/noodles/run/xenon/dynamic_pool.py", line 15, in <module>
    from .xenon import (XenonKeeper, XenonConfig, XenonScheduler)
  File "/home/felipe/prototype/noodles/noodles/run/xenon/xenon.py", line 16, in <module>
    xenon.init(log_level='ERROR')  # noqa
  File "/home/felipe/miniconda3/envs/qmworks/lib/python3.5/site-packages/xenon/__init__.py", line 69, in init
    raise ValueError("Classpath does not correctly specify Xenon and "
ValueError: Classpath does not correctly specify Xenon and its dependencies. This exception is fatal: calling init again will not resolve this error
```

**Comment by blootsvoets** [comment]
Hmm.. Could you try updating pyxenon from github and reinstalling with
```
pip install -U .
```
or even just uninstall pyxenon, go to the noodles directory and install with:
```
pip install ".[xenon]"
```
Either one should work.

**Comment by felipeZ** [comment]
You update have solved the issue. Thanks!
